name: AoC22 - C++ & Abseil
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: cppcheck installation
      run: sudo apt update && sudo apt -y install cppcheck

    - name: AoC22
      run: cd AoC22/cpp && cmake . && cmake --build . --target all && ./aoc22 -d yes && cd ..
