name: C++ Tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    # runs-on: ubuntu-latest
    # so far latest is 20.04 not 22.04 yet
    runs-on: ubuntu-22.04
      # - cxx: clang++
    
    steps:
    - uses: actions/checkout@v2

    - name: cppcheck installation (used in AoC15 and AoC20)
      run: sudo apt update && sudo apt -y install cppcheck

    # - name: Catch2 installation (used in AoC15 and AoC20)
      # unknown package - run: sudo apt update && sudo apt -y install catch2
    #  run: git clone https://github.com/catchorg/Catch2.git && cd Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install && cd ..

    - name: AoC20
      run: cd AoC20 && cmake . && cmake --build . --target all && ./aoc20 && cd ..

    # - name: AoC19
    #  run: cd AoC19/cpp && cmake . && make all && ./aoc19 && cd ../..

    - name: AoC15
      run: cd AoC15 && cmake . && cmake --build . --target all && ./aoc15 && cd ..
