name: build and run tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Catch2 installation (used in AoC15 and AoC20 )
      run: sudo apt update && sudo apt -y install catch2

    - name: AoC20
      run: cd AoC20 && cmake . && cmake --build . --target all && ./aoc20 && cd ..

    - name: AoC15
      run: cd AoC15 && cmake . && cmake --build . --target all && ./aoc15 && cd ..
